services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - 27017:27017
    volumes:
      - /data/db
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
  auction-svc:
    image: auction-svc:latest
    build:
     context: .
     dockerfile: src/AuctionService/Dockerfile
    ports:
      - 7001:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=Http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=Auctions
      - IdentityServiceUrl=http://identity-scv
    depends_on:
      - postgres
      - rabbitmq
  search-svc:
    image: search-svc:latest
    build:
     context: .
     dockerfile: src/SearchService/Dockerfile
    ports:
      - 7002:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=Http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDBConnectionString=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-svc
    depends_on:
      - mongodb
      - rabbitmq
  identity-svc:
    image: identity-svc:latest
    build:
     context: .
     dockerfile: src/IdentityService/Dockerfile
    ports:
      - 5000:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=Identity
    depends_on:
      - postgres
  gateway-svc:
    image: gateway-svc:latest
    build:
     context: .
     dockerfile: src/GatewayService/Dockerfile
    ports:
      - 6001:80
    environment: 
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80

# volumes:
#   pgdata:
#   mongodata: